[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api"
  to = "https://rentday.coderdreams.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect  